# Generated by Django 4.1.5 on 2023-01-05 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chaniago', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='crud',
        ),
        migrations.DeleteModel(
            name='Maps',
        ),
    ]
